rimov/crm/urls.py
from django.urls import include, path
from rimov.crm import views as v


app_name = 'crm'


pf_urlpatterns = [
    path('', v.pf_list, name='pf_list'),
    path('add/', v.PFCreate.as_view(), name='pf_create'),
    # path('<int:pk>/', v.pf_detail, name='pf_detail'),
    path('<int:pk>/update/', v.PFUpdate.as_view(), name='pf_update'),
    path('<int:pk>/delete/', v.pf_delete, name='pf_delete'),
]

pj_urlpatterns = [
    path('', v.pj_list, name='pj_list'),
    path('add/', v.PJCreate.as_view(), name='pj_create'),
    # path('<int:pk>/', v.pj_detail, name='pj_detail'),
    path('<int:pk>/update/', v.PJUpdate.as_view(), name='pj_update'),
    path('<int:pk>/delete/', v.pj_delete, name='pj_delete'),
]


urlpatterns = [
    path('pessoa-fisica/', include(pf_urlpatterns)),
    path('pessoa-juridica/', include(pj_urlpatterns)),
]

rimov/imovel/urls.py
from django.urls import path
from rimov.imovel import views as v


app_name = 'imovel'


urlpatterns = [
    path('', v.imovel_list, name='imovel_list'),
    path('add/', v.imovel_create, name='imovel_create'),
    path('<int:id>/', v.imovel_detail, name='imovel_detail'),
    path('<int:id>/update/', v.imovel_update, name='imovel_update'),
    path('<int:id>/delete/', v.imovel_delete, name='imovel_delete'),
    path('imagem/<int:id>/update/', v.imagem_update, name='imagem_update'),
]

rimov/urls.py
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('', include('rimov.core.urls', namespace='core')),
    path('crm/', include('rimov.crm.urls', namespace='crm')),
    path('imovel/', include('rimov.imovel.urls', namespace='imovel')),
    path('usuario/', include('rimov.usuario.urls', namespace='usuario')),
    path('media/<path>/', serve, {'document_root = settings.MEDIA_ROOT'}),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rimov/crm/models.py
from django.db import models
from rimov.core.models import Endereco


class Pessoa(Endereco):
    pass

    class Meta:
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'


class PessoaFisica(Pessoa):
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100, null=True, blank=True)
    cpf = models.CharField('CPF', max_length=11, unique=True, null=True, blank=True)
    rg = models.CharField('RG', max_length=11, null=True, blank=True)

    class Meta:
        ordering = ('nome',)
        verbose_name = 'pessoa física'
        verbose_name_plural = 'pessoas físicas'

    def __str__(self):
        return f'{self.nome} - {self.sobrenome}'


class PessoaJuridica(Pessoa):
    razao_social = models.CharField('razão social', max_length=100)
    nome_fantasia = models.CharField('nome fantasia', max_length=100, null=True, blank=True)
    cnpj = models.CharField('CNPJ', max_length=14, unique=True, null=True, blank=True)
    inscricao_estadual = models.CharField('inscrição estadual', max_length=25, null=True, blank=True)
    inscricao_municipal = models.CharField('inscrição municipal', max_length=25, null=True, blank=True)

    class Meta:
        ordering = ('razao_social',)
        verbose_name = 'pessoa jurídica'
        verbose_name_plural = 'pessoas jurídicas'

    def __str__(self):
        return self.razao_social

rimov/crm/forms.py
from django import forms
from .models import PessoaFisica, PessoaJuridica


class PessoaFisicaForm(forms.ModelForm):

    class Meta:
        model = PessoaFisica
        fields = (
            'nome',
            'sobrenome',
            'cpf',
            'rg',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'cep',
        )


class PessoaJuridicaForm(forms.ModelForm):

    class Meta:
        model = PessoaJuridica
        fields = (
            'razao_social',
            'nome_fantasia',
            'cnpj',
            'inscricao_estadual',
            'inscricao_municipal',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'cep',
        )

rimov/crm/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from .forms import PessoaFisicaForm, PessoaJuridicaForm
from .models import PessoaFisica, PessoaJuridica


def pf_list(request):
    template_name = 'crm/pessoa_fisica_list.html'
    object_list = PessoaFisica.objects.all()
    context = {'object_list': object_list}
    return render(request, template_name, context)


class PFCreate(CreateView):
    model = PessoaFisica
    form_class = PessoaFisicaForm
    success_url = reverse_lazy('crm:pf_list')


class PFUpdate(UpdateView):
    model = PessoaFisica
    form_class = PessoaFisicaForm
    success_url = reverse_lazy('crm:pf_list')


def pf_delete(request, pk):
    pf = PessoaFisica.objects.get(pk=pk)
    pf.delete()
    return redirect('crm:pf_list')


def pj_list(request):
    template_name = 'crm/pessoa_juridica_list.html'
    object_list = PessoaJuridica.objects.all()
    context = {'object_list': object_list}
    return render(request, template_name, context)


class PJCreate(CreateView):
    model = PessoaJuridica
    form_class = PessoaJuridicaForm
    success_url = reverse_lazy('crm:pj_list')


class PJUpdate(UpdateView):
    model = PessoaJuridica
    form_class = PessoaJuridicaForm
    success_url = reverse_lazy('crm:pj_list')


def pj_delete(request, pk):
    pj = PessoaJuridica.objects.get(pk=pk)
    pj.delete()
    return redirect('crm:pj_list')

rimov/crm/templates/crm/pessoa_fisica_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        {{ imovel.titulo }}
        <div class="btn-group float-right">
          <button class="btn btn-setting dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="icon-settings"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div>
        <a class="pull-right btn btn-sm btn-primary mr-2" style="color: white" href="{% url 'imovel:imovel_update' imovel.pk %}">
          <i class="fa fa-edit"></i> Editar
        </a>        
        <span class="badge badge-success pull-right mr-2">Disponível</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-6">
            <img src="{{ imovel.first_image.imagem.url }}" width="200px">
          </div>
          <br>
          <div class="col-6">
            <h4><small><span class="text-muted">Propriedade:</span></small>
              {{ imovel.propriedade }}
            </h4>
            <h4><small><span class="text-muted">Negócio:</span></small>
              {{ imovel.negocio }}
            </h4>
            <h4><small><span class="text-muted">Categoria:</span></small>
              {{ imovel.categoria }}
            </h4>
            <h4><small><span class="text-muted">Valor:</span></small>
              {{ imovel.valor }}
            </h4>           
          </div>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <h4>Características</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Área:</span> {{ imovel.area }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Quartos:</span> {{ imovel.num_quarto }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Banheiros:</span> {{ imovel.num_banheiro }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Vagas:</span> {{ imovel.num_vaga }}</li>
          </ul>
        </li>
        <li class="list-group-item">
          <h4>Dados Gerais</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Localização Aprox:</span> {{ imovel.localizacao }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Endereço:</span> {{ imovel.endereco }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Corretor:</span> {{ imovel.corretor.usuario.get_full_name }}</li>
          </ul>
        </li>
        <li class="list-group-item">
          <h4>Descrição</h4>
          <p class="text-justify">{{imovel.descricao}}</p>
        </li>
      </ul>
    </div>
  </div>
  <!-- <div class="col-lg-3">
    <div class="card">
      <div class="card-header">
        Contacts
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item no-border">
            <span class="badge badge-warning">type</span> 11 98765-4321
            <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
              <i class="fa fa-edit" style="margin-left: 10px;"></i>
            </span>
          </li>
        </ul>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        Title
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="text-muted">Label:</span> <span class="lead">text</span>
                <span class="span-is-link float-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div> -->
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        Video:
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Adicionar</span>
      </div>
      <div>
        <!-- card-body -->
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="lead"><b>link:</b> {{imovel.video}}</span>
                <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
              <span class="text-muted">Imagens:</span>             
              <li class="list-group-item li-line pl-0 pr-0">
                <br>                
                {% for item in imovel.imagem_imoveis.all %}
                <!-- {{ iterador.campo }} -->
                  {% if item.imagem %}
                    <img src="{{ item.imagem.url }}" width="180">
                  {% endif %}
                {% endfor %} 
                <br>
                
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
{% include "includes/modal.html" %}
{% endblock content %}

rimov/crm/templates/crm/pessoa_fisica_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block css %}
<style>
  input, textarea {
    text-transform: uppercase;
  }
  span.required:after {
    content: "*";
    color: red;
  }
</style>
{% endblock css %}
{% block content %}
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <strong>Imóvel</strong>
        <!-- <small>Form</small> -->
      </div>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
              {% if field.field.required %}
              <span class="required">{{ field.label }} </span>
              {% else %}
              {{ field.label }}
              {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
          {% endfor %}
          <label for="imagens">Imagens:</label> <input type="file" name="imagens" multiple="">
          <br>
          <input type="button" value="Voltar" class="btn btn-info" onClick="history.go(-1)"> <input type="submit" class="btn btn-success" value="Salvar">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

rimov/crm/templates/crm/pessoa_fisica_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Pessoa Física
        <span class="float-right">1 of 10 resultados (100 total)</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-auto">
            <a class="btn btn-primary" href="{% url 'crm:pf_create' %}">
              <i class="fa fa-plus"></i>
              Adicionar
            </a>
          </div>
          <div class="col">
            <form action="." method="GET">
              <div class="row">
                <div class="col p-ari-5">
                  <input name="search" class="form-control mb-2" type="text" placeholder="Busca..." />
                </div>
                <div class="col-auto">
                  <button class="btn btn-success mb-2" type="submit">OK</button>
                  <button class="btn btn-link mb-2">Limpar</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- TABLE -->
        <table class="table table-responsive-sm table-hover table-striped">
          <thead>
            <tr>
              <th>NOME COMPLETO</th>
              <th>CPF</th>
              <th class="text-center">AÇÕES</th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
              <tr>
                <td>
                  <a href="{ url 'crm:pf_detail' object.pk %}">{{ object }}</a>
                </td>
                <td>{{ object.cpf|default:'---' }}</td>
                <td width="120px">
                  <div class="botoes list">
                    <a href="{% url 'crm:pf_update' object.pk %}" class="btn btn-primary"><i class="icon-pencil"></i></a>
                    <span data-url="{% url 'crm:pf_delete' object.pk %}" class="btn btn-danger delete"><i class="icon-trash"></i></span>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <!-- pagination -->
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
  <script>
    $('.delete').click(function() {
      const url = $(this).data("url");
      Swal.fire({
        title: 'Deseja deletar este item?',
        showCancelButton: true,
        confirmButtonText: `Sim`,
      }).then((result) => {
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
          // Swal.fire('Saved!', '', 'success')
          window.location.href = url
        }
      })
    });

    window.setTimeout(function() {
      $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
      });
    }, 3000);
  </script>
{% endblock js %}

rimov/crm/templates/crm/pessoa_juridica_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        {{ imovel.titulo }}
        <div class="btn-group float-right">
          <button class="btn btn-setting dropdown-toggle p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="icon-settings"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div>
        <a class="pull-right btn btn-sm btn-primary mr-2" style="color: white" href="{% url 'imovel:imovel_update' imovel.pk %}">
          <i class="fa fa-edit"></i> Editar
        </a>        
        <span class="badge badge-success pull-right mr-2">Disponível</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-6">
            <img src="{{ imovel.first_image.imagem.url }}" width="200px">
          </div>
          <br>
          <div class="col-6">
            <h4><small><span class="text-muted">Propriedade:</span></small>
              {{ imovel.propriedade }}
            </h4>
            <h4><small><span class="text-muted">Negócio:</span></small>
              {{ imovel.negocio }}
            </h4>
            <h4><small><span class="text-muted">Categoria:</span></small>
              {{ imovel.categoria }}
            </h4>
            <h4><small><span class="text-muted">Valor:</span></small>
              {{ imovel.valor }}
            </h4>           
          </div>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <h4>Características</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Área:</span> {{ imovel.area }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Quartos:</span> {{ imovel.num_quarto }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Banheiros:</span> {{ imovel.num_banheiro }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Vagas:</span> {{ imovel.num_vaga }}</li>
          </ul>
        </li>
        <li class="list-group-item">
          <h4>Dados Gerais</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item no-border"><span class="text-muted">Localização Aprox:</span> {{ imovel.localizacao }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Endereço:</span> {{ imovel.endereco }}</li>
            <li class="list-group-item no-border"><span class="text-muted">Corretor:</span> {{ imovel.corretor.usuario.get_full_name }}</li>
          </ul>
        </li>
        <li class="list-group-item">
          <h4>Descrição</h4>
          <p class="text-justify">{{imovel.descricao}}</p>
        </li>
      </ul>
    </div>
  </div>
  <!-- <div class="col-lg-3">
    <div class="card">
      <div class="card-header">
        Contacts
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item no-border">
            <span class="badge badge-warning">type</span> 11 98765-4321
            <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
              <i class="fa fa-edit" style="margin-left: 10px;"></i>
            </span>
          </li>
        </ul>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        Title
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Add</span>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="text-muted">Label:</span> <span class="lead">text</span>
                <span class="span-is-link float-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div> -->
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        Video:
        <span class="pull-right badge badge-success i-is-link" data-toggle="modal" data-target="#mymodal"><i class="fa fa-plus"></i> Adicionar</span>
      </div>
      <div>
        <!-- card-body -->
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <ul class="list-group list-group-flush">
              <li class="list-group-item no-border li-line pl-0 pr-0">
                <span class="lead"><b>link:</b> {{imovel.video}}</span>
                <span class="span-is-link pull-right" data-toggle="modal" data-target="#mymodal">
                  <i class="fa fa-edit" style="margin-left: 10px;"></i>
                </span>
              </li>
              <span class="text-muted">Imagens:</span>             
              <li class="list-group-item li-line pl-0 pr-0">
                <br>                
                {% for item in imovel.imagem_imoveis.all %}
                <!-- {{ iterador.campo }} -->
                  {% if item.imagem %}
                    <img src="{{ item.imagem.url }}" width="180">
                  {% endif %}
                {% endfor %} 
                <br>
                
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
{% include "includes/modal.html" %}
{% endblock content %}

rimov/crm/templates/crm/pessoa_juridica_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block css %}
<style>
  input, textarea {
    text-transform: uppercase;
  }
  span.required:after {
    content: "*";
    color: red;
  }
</style>
{% endblock css %}
{% block content %}
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <strong>Imóvel</strong>
        <!-- <small>Form</small> -->
      </div>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
              {% if field.field.required %}
              <span class="required">{{ field.label }} </span>
              {% else %}
              {{ field.label }}
              {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
          {% endfor %}
          <label for="imagens">Imagens:</label> <input type="file" name="imagens" multiple="">
          <br>
          <input type="button" value="Voltar" class="btn btn-info" onClick="history.go(-1)"> <input type="submit" class="btn btn-success" value="Salvar">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

rimov/crm/templates/crm/pessoa_juridica_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Pessoa Jurídica
        <span class="float-right">1 of 10 resultados (100 total)</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-auto">
            <a class="btn btn-primary" href="{% url 'crm:pj_create' %}">
              <i class="fa fa-plus"></i>
              Adicionar
            </a>
          </div>
          <div class="col">
            <form action="." method="GET">
              <div class="row">
                <div class="col p-ari-5">
                  <input name="search" class="form-control mb-2" type="text" placeholder="Busca..." />
                </div>
                <div class="col-auto">
                  <button class="btn btn-success mb-2" type="submit">OK</button>
                  <button class="btn btn-link mb-2">Limpar</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- TABLE -->
        <table class="table table-responsive-sm table-hover table-striped">
          <thead>
            <tr>
              <th>RAZÃO SOCIAL</th>
              <th>NOME FANTASIA</th>
              <th>CNPJ</th>
              <th class="text-center">AÇÕES</th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
              <tr>
                <td>
                  <a href="{ url 'crm:pj_detail' object.pk %}">{{ object.razao_social }}</a>
                </td>
                <td>{{ object.nome_fantasia|default:'---' }}</td>
                <td>{{ object.cnpj|default:'---' }}</td>
                <td width="120px">
                  <div class="botoes list">
                    <a href="{% url 'crm:pj_update' object.pk %}" class="btn btn-primary"><i class="icon-pencil"></i></a>
                    <span data-url="{% url 'crm:pj_delete' object.pk %}" class="btn btn-danger delete"><i class="icon-trash"></i></span>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <!-- pagination -->
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
  <script>
    $('.delete').click(function() {
      const url = $(this).data("url");
      Swal.fire({
        title: 'Deseja deletar este item?',
        showCancelButton: true,
        confirmButtonText: `Sim`,
      }).then((result) => {
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
          // Swal.fire('Saved!', '', 'success')
          window.location.href = url
        }
      })
    });

    window.setTimeout(function() {
      $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
      });
    }, 3000);
  </script>
{% endblock js %}

rimov/crm/templates/crm/pessoafisica_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block css %}
<style>
  input, textarea {
    text-transform: uppercase;
  }
  span.required:after {
    content: "*";
    color: red;
  }
</style>
{% endblock css %}
{% block content %}
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <strong>Pessoa Física</strong>
        <!-- <small>Form</small> -->
      </div>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
              {% if field.field.required %}
              <span class="required">{{ field.label }} </span>
              {% else %}
              {{ field.label }}
              {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
          {% endfor %}
          <input type="button" value="Voltar" class="btn btn-info" onClick="history.go(-1)"> <input type="submit" class="btn btn-success" value="Salvar">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

rimov/crm/templates/crm/pessoajuridica_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block css %}
<style>
  input, textarea {
    text-transform: uppercase;
  }
  span.required:after {
    content: "*";
    color: red;
  }
</style>
{% endblock css %}
{% block content %}
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <strong>Pessoa Jurídica</strong>
        <!-- <small>Form</small> -->
      </div>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
              {% if field.field.required %}
              <span class="required">{{ field.label }} </span>
              {% else %}
              {{ field.label }}
              {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
            {% endfor %}
          </div>
          {% endfor %}
          <input type="button" value="Voltar" class="btn btn-info" onClick="history.go(-1)"> <input type="submit" class="btn btn-success" value="Salvar">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}